### ISSUE TITLE
nothing is downloaded

### ISSUE THREAD

**Issue by Goldsucher** [flokol120/South-Park-Downloader#5]
Hi flokol120,
I am trying to use this downloader but with the latest release no download is started. Do I have to install some other dependencies or should it work out of the box?
Is there already a compiled version of the rewritten branch?

thank you!

EDIT: Okay, the Problem is related to MacOS (10.13.5). On Windows 10 the downloads are working (but only the german ones)

**Comment by flokol120** [comment]
Hello @Goldsucher,

the compiled version is working out of the box, but only on Linux and Windows because I am not able to test this on any Mac. 

The rewritten version is currently WIP and there is none working version of it yet, not even if you choose to build it yourself. This is due to an outdated/broken dependency I was going to use. I am currently lurking for an alternative.

Please understand that I won't fix your issue of the not working downloads in the english language in the current version. The rewritten version, once finished, should fix all those issues.

**Comment by flokol120** [comment]
edit:
The current state of the rewritten version is now able to download episodes in a very basic way. But it's most likely only working for linux at the moment.

**Comment by flokol120** [comment]
edit:

The first [pre-release rewritten version](https://github.com/flokol120/South-Park-Downloader/releases/tag/2.0.0) is avalible now. It should fix many problems from the previous one, but it also has many new ones.

**Comment by flokol120** [comment]
@jmtatsch please provide your Distro.

**Comment by jmtatsch** [comment]
Ubuntu 18.04 server, ui via X11 on mac. 
But don't worry. I have written my own downloader now :)
